### ISSUE TITLE
how to get the the file of BALMS in projects?

### ISSUE THREAD

**Issue by pantingchn** [Majiker/BalancedMetaSoftmax-InstanceSeg#1]
hi, i follow the steps to install the detectron2, but no file named BALMS/ is in /detectron2/projects/. How to get the BALMS/ ?

**Comment by jiawei-ren** [comment]
Please clone this repo first, then follow the steps to "install detectron2 from a local clone". 
Specifically, you may take the following steps:
1. Clone this repo by `git clone https://github.com/Majiker/BalancedMetaSoftmax-InstanceSeg.git`
2. Install detectron2 by `python -m pip install -e BalancedMetaSoftmax-InstanceSeg`
3. Install other dependencies, and go into the repo directory by `cd BalancedMetaSoftmax-InstanceSeg`

Then you should be able to run the training and inference commands.
